---
# journald

- hosts:
    all
  become:
    yes

  tasks:

  - name: Create config dropin directory, if needed.
    ansible.builtin.file:
      path: /etc/systemd/journald.conf.d
      owner: root
      group: root
      mode: 0755
      state: directory
    
  - name: Copy the journald dropins.
    ansible.builtin.copy:
      src: "{{item}}"
      dest: /etc/systemd/journald.conf.d/
      owner: root
      group: root
      mode:  0644
    loop:
      # ForwardToSyslog=yes normally by default, but to be sure:
      - /etc/ansible/files/etc/systemd/journald.conf.d/10-forwardtosyslog.conf
    notify: restart journald

  handlers:

  - name: restart journald
    ansible.builtin.service:
      name: systemd-journald
      state: restarted
