---
# ssh configuration tweaks

- hosts:
    all
  become:
    yes

  tasks:

  - name: disable password authentication
    lineinfile:
      path:
        /etc/ssh/sshd_config
      regexp:
        '^PasswordAuthentication '
      line:
        'PasswordAuthentication no'
      insertafter:
        '^#PasswordAuthentication[ \t]+yes'
      backup:
        yes
      validate:
        /usr/sbin/sshd -t -f %s
    notify:
      reload sshd

  - name: disable challenge-response authentication
    lineinfile:
      path:
        /etc/ssh/sshd_config
      regexp:
        '^ChallengeResponseAuthentication '
      line:
        'ChallengeResponseAuthentication no'
      insertafter:
        '^#ChallengeResponseAuthentication[ \t]+yes'
      backup:
        yes
      validate:
        /usr/sbin/sshd -t -f %s
    notify:
      reload sshd

  - name: limit root logins to prohibit-password
    lineinfile:
      path:
        /etc/ssh/sshd_config
      regexp:
        '^PermitRootLogin '
      line:
        'PermitRootLogin prohibit-password'
      insertafter:
        '^#PermitRootLogin[ \t]+yes'
      backup:
        yes
      validate:
        /usr/sbin/sshd -t -f %s
    notify:
      reload sshd

  - name: root authorized_keys permissions
    block:
      - name: check if there's a root authorized_keys file
        stat:
          path:
            /root/.ssh/authorized_keys
        register:
          st

      - name: check file permissions
        file:
          path:
            /root/.ssh/authorized_keys
          owner:
            root
          group:
            root
          mode:
            '0600'
        when:
          st.stat.exists
    
  handlers:
    - name:
        reload sshd
      service:
        name:
          ssh
        state:
          reloaded
          
