---
# Set up automatic reboots at 7pm on the third Wednesday of the month

- hosts:
    all
  become:
    yes

  tasks:
    
  - name: copy thirdwedreboot.sh script
    ansible.builtin.copy:
      src: /etc/ansible/files/usr/local/sbin/thirdwedreboot.sh
      dest: /usr/local/sbin/thirdwedreboot.sh
      owner: root
      group: root
      mode:  0755
        
  - name: copy systemd service file
    ansible.builtin.copy:
      src: /etc/ansible/files/etc/systemd/system/thirdwedreboot.service
      dest: /etc/systemd/system/thirdwedreboot.service
      owner: root
      group: root
      mode:  0644
    notify:
      reload systemd

  - name: copy systemd timer file
    ansible.builtin.copy:
      src: /etc/ansible/files/etc/systemd/system/thirdwedreboot.timer
      dest: /etc/systemd/system/thirdwedreboot.timer
      owner: root
      group: root
      mode: 0644
    notify: reload systemd

  - name: enable and start timer
    ansible.builtin.systemd:
      name: thirdwedreboot.timer
      state: started
      enabled: yes

  handlers:

  - name: reload systemd
    ansible.builtin.systemd:
      daemon_reload: yes
