---
# timezone
#
# It's a America/Phoenix timezone world for us, even in eu-north-1

- hosts:
    all
  become:
    yes

  tasks:
  - name: Check the current timezone,
    ansible.builtin.command: "timedatectl show --property=Timezone"
    register: tz
    changed_when: false

  - name: print it
    debug:
      msg: "{{ tz.stdout }}"

  - name: and set it to America/Phoenix if need be.
    ansible.builtin.command: "timedatectl set-timezone America/Phoenix"
    when: "'Timezone=America/Phoenix' not in tz.stdout"
#    changed_when: "'Timezone=America/Phoenix' not in tz.stdout"
    notify:
      - restart crond

  handlers:
    - name: restart crond
      ansible.builtin.service:
        name: cron
        state: restarted
